### ISSUE TITLE
Fully support returning Response<CustomMsg> 

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/sylvia#140]
I got some code to compile with Sylvia 0.4.0 and no `mt` returning Response<CustomMsg> from instantiate (and in lib.rs)

When I updated to Sylvia 0.4.2 with `mt` flag enabled, it returned a compiler error.

The proc macros for the contract itself seem to handle it, seems to be more about mt.

**Comment by ethanfrey** [comment]
My code

```rust
    #[msg(instantiate)]
    pub fn instantiate(
        &self,
        ctx: InstantiateCtx,
        denom: String,
    ) -> Result<Response<VirtualStakeCustomMsg>, ContractError> {
     ///
   }
```

`Cargo.toml`:

```toml
[dev-dependencies]
sylvia = { workspace = true, features = ["mt"]  }
```

The error message on `cargo test` (`cargo build` is fine):

```
error[E0308]: mismatched types
  --> contracts/consumer/virtual-staking/src/contract.rs:39:1
   |
39 | #[contract]
   | ^^^^^^^^^^^
   | |
   | expected `Result<Response, Error>`, found `Result<Response<...>, ...>`
   | expected `Result<Response, sylvia::anyhow::Error>` because of return type
   |
   = note: expected enum `Result<Response<cosmwasm_std::Empty>, sylvia::anyhow::Error>`
              found enum `Result<Response<VirtualStakeCustomMsg>, _>`
   = note: this error originates in the attribute macro `contract` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by hashedone** [comment]
Closes in favor of #157
